# SPDX-License-Identifier: GPL-3.0-or-later OR Commercial
"""
Generate random ChaCha20-Poly1305 AEAD test vectors for the C++ harness.

Output: a C++ header (random_vectors.h) defining a static table of
{key, nonce, aad, plaintext, ciphertext, tag} tuples. The harness in
sim_main_aead.cpp includes this header and runs each vector through the
DUT, comparing against the reference computed by Python's
`cryptography.hazmat.primitives.ciphers.aead.ChaCha20Poly1305`.

Strategy:
  * 100 random vectors, lengths drawn from:
      - tail of [0..63]            (single-block boundary)
      - random [64..256]           (multi-block)
  * AAD length: 0, 12 (canonical RFC), and a small random in [0..32]
  * Each vector: encrypt -> store ciphertext + tag

Run: `python tb/gen_random_vectors.py > tb/random_vectors.h`
(invoked by `make regen_vectors`).

This script is deterministic given the seed below.
"""

import os
import random
import sys

from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305


def main() -> int:
    random.seed(0xCC20A1B5)

    n_total = 100
    out = sys.stdout
    out.write("// SPDX-License-Identifier: GPL-3.0-or-later OR Commercial\n")
    out.write("// AUTO-GENERATED by tb/gen_random_vectors.py.\n"
              "// Do not edit by hand; regenerate with `make regen_vectors`.\n")
    out.write("#pragma once\n")
    out.write("#include <cstdint>\n")
    out.write("#include <cstddef>\n\n")
    out.write("struct AeadVec {\n")
    out.write("    const uint8_t* key;     // 32 bytes\n")
    out.write("    const uint8_t* nonce;   // 12 bytes\n")
    out.write("    const uint8_t* aad;     // aad_len bytes\n")
    out.write("    size_t         aad_len;\n")
    out.write("    const uint8_t* pt;      // pt_len bytes\n")
    out.write("    size_t         pt_len;\n")
    out.write("    const uint8_t* ct;      // pt_len bytes\n")
    out.write("    const uint8_t* tag;     // 16 bytes\n")
    out.write("};\n\n")

    arena = bytearray()
    pos_table = []  # parallel: list of (key_off, nonce_off, aad_off, aad_len,
                    #                    pt_off, pt_len, ct_off, tag_off)

    for i in range(n_total):
        key   = bytes(random.randint(0, 255) for _ in range(32))
        nonce = bytes(random.randint(0, 255) for _ in range(12))

        # AAD: mix of 0, 12 (canonical), small random 1..32
        choice = i % 4
        if choice == 0:
            aad_len = 0
        elif choice == 1:
            aad_len = 12
        else:
            aad_len = random.randint(1, 32)
        aad = bytes(random.randint(0, 255) for _ in range(aad_len))

        # PT length: edge cases + random
        if i < 8:
            pt_len = i  # 0,1,2,3,4,5,6,7
        elif i < 16:
            pt_len = 56 + (i - 8)  # 56..63 (single-block boundary)
        elif i < 24:
            pt_len = 64 + (i - 16)  # 64..71 (just past one block)
        else:
            pt_len = random.randint(0, 256)
        pt = bytes(random.randint(0, 255) for _ in range(pt_len))

        cha = ChaCha20Poly1305(key)
        ct_and_tag = cha.encrypt(nonce, pt, aad if aad_len > 0 else None)
        ct, tag = ct_and_tag[:-16], ct_and_tag[-16:]
        assert len(ct) == pt_len
        assert len(tag) == 16

        offs = []
        for blob in (key, nonce, aad, pt, ct, tag):
            offs.append(len(arena))
            arena.extend(blob)
        pos_table.append((offs, aad_len, pt_len))

    # Sentinel byte so &arena[N] is always a valid pointer
    arena.append(0)

    out.write("static const uint8_t kAeadArena[] = {\n")
    for i in range(0, len(arena), 16):
        chunk = arena[i:i+16]
        out.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    out.write("};\n\n")

    out.write("static const AeadVec kAeadVectors[] = {\n")
    for offs, aad_len, pt_len in pos_table:
        key_off, nonce_off, aad_off, pt_off, ct_off, tag_off = offs
        out.write(f"    {{ kAeadArena + {key_off}, kAeadArena + {nonce_off}, "
                  f"kAeadArena + {aad_off}, {aad_len}u, "
                  f"kAeadArena + {pt_off}, {pt_len}u, "
                  f"kAeadArena + {ct_off}, kAeadArena + {tag_off} }},\n")
    out.write("};\n\n")
    out.write(f"static constexpr size_t kAeadVectorCount ="
              f" sizeof(kAeadVectors) / sizeof(kAeadVectors[0]);\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
